# These are supported funding model platforms

github: backrat13

cashapp: $frankhymer85
Email:frankhymer2025@proton.me

# I'll leave a phone number, but know this: I WILL NOT EVER ANSWER MY PHONE TO ANYONE WITHOUT AN APPOINTMENT. TO MUCH SPAM IN THE PAST,
NOTE: If trying to reach me to sell something to me, I WILL NOT respond. I will classify it as spam and block the number used.
If you are looking for someone to join a project, I am currently looking to be part of something. Open-source OR paid work, I would appreciate the opportunity to make a difference on you project and/or team

 SO TEXT ME ON Whatsapp #: 856-504-7989  just text first and/or email. AGAIN, I will NEVER answer a random phone call that wasn't set up. 

 Thanks, F.Hymer 'Backrat'
